---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    workload.openshift.io/allowed: management  # Environment-specific - can be absent if workload partitioning is not used