---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
spec:
  channel: "stable-6.2"
  name: cluster-logging
  source: redhat-operators-disconnected  # Environment-specific - any valid catalog source allowed
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic